const pokemones = {
    Bulbasaur: ["Planta", "Veneno"],
    Ivysaur: ["Planta", "Veneno"],
    Venusaur: ["Planta", "Veneno"],
    Charmander: ["Fuego"],
    Charmeleon: ["Fuego"],
    Charizard: ["Fuego", "Volador"],
    Squirtle: ["Agua"],
    Wartortle: ["Agua"],
    Blastoise: ["Agua"],
    Caterpie: ["Bicho"],
    Metapod: ["Bicho"],
    Butterfree: ["Bicho", "Volador"],
    Weedle: ["Bicho", "Veneno"],
    Kakuna: ["Bicho", "Veneno"],
    Beedrill: ["Bicho", "Veneno"],
    Pidgey: ["Normal", "Volador"],
    Pidgeotto: ["Normal", "Volador"],
    Pidgeot: ["Normal", "Volador"],
    Rattata: ["Normal"],
    Raticate: ["Normal"],
    Spearow: ["Normal", "Volador"],
    Fearow: ["Normal", "Volador"],
    Ekans: ["Veneno"],
    Arbok: ["Veneno"],
    Pikachu: ["Eléctrico"],
    Raichu: ["Eléctrico"],
    Sandshrew: ["Tierra"],
    Sandslash: ["Tierra"],
    Nidoran_h: ["Veneno"],
    Nidorina: ["Veneno"],
    Nidoqueen: ["Veneno", "Tierra"],
    Nidoran_m: ["Veneno"],
    Nidorino: ["Veneno"],
    Nidoking: ["Veneno", "Tierra"],
    Clefairy: ["Normal"],
    Clefable: ["Normal"],
    Vulpix: ["Fuego"],
    Ninetales: ["Fuego"],
    Jigglypuff: ["Normal"],
    Wigglytuff: ["Normal"],
    Zubat: ["Veneno", "Volador"],
    Golbat: ["Veneno", "Volador"],
    Oddish: ["Planta", "Veneno"],
    Gloom: ["Planta", "Veneno"],
    Vileplume: ["Planta", "Veneno"],
    Paras: ["Bicho", "Planta"],
    Parasect: ["Bicho", "Planta"],
    Venonat: ["Bicho", "Veneno"],
    Venomoth: ["Bicho", "Veneno"],
    Diglett: ["Tierra"],
    Dugtrio: ["Tierra"],
    Meowth: ["Normal"],
    Persian: ["Normal"],
    Psyduck: ["Agua"],
    Golduck: ["Agua"],
    Mankey: ["Lucha"],
    Primeape: ["Lucha"],
    Growlithe: ["Fuego"],
    Arcanine: ["Fuego"],
    Poliwag: ["Agua"],
    Poliwhirl: ["Agua"],
    Poliwrath: ["Agua", "Lucha"],
    Abra: ["Psíquico"],
    Kadabra: ["Psíquico"],
    Alakazam: ["Psíquico"],
    Machop: ["Lucha"],
    Machoke: ["Lucha"],
    Machamp: ["Lucha"],
    Bellsprout: ["Planta", "Veneno"],
    Weepinbell: ["Planta", "Veneno"],
    Victreebel: ["Planta", "Veneno"],
    Tentacool: ["Agua", "Veneno"],
    Tentacruel: ["Agua", "Veneno"],
    Geodude: ["Roca", "Tierra"],
    Graveler: ["Roca", "Tierra"],
    Golem: ["Roca", "Tierra"],
    Ponyta: ["Fuego"],
    Rapidash: ["Fuego"],
    Slowpoke: ["Agua", "Psíquico"],
    Slowbro: ["Agua", "Psíquico"],
    Magnemite: ["Eléctrico", "Acero"],
    Magneton: ["Eléctrico", "Acero"],
    Farfetch: ["Normal", "Volador"],
    Doduo: ["Normal", "Volador"],
    Dodrio: ["Normal", "Volador"],
    Seel: ["Agua"],
    Dewgong: ["Agua", "Hielo"],
    Grimer: ["Veneno"],
    Muk: ["Veneno"],
    Shellder: ["Agua"],
    Cloyster: ["Agua", "Hielo"],
    Gastly: ["Fantasma", "Veneno"],
    Haunter: ["Fantasma", "Veneno"],
    Gengar: ["Fantasma", "Veneno"],
    Onix: ["Roca", "Tierra"],
    Drowzee: ["Psíquico"],
    Hypno: ["Psíquico"],
    Krabby: ["Agua"],
    Kingler: ["Agua"],
    Voltorb: ["Eléctrico"],
    Electrode: ["Eléctrico"],
    Exeggcute: ["Planta", "Psíquico"],
    Exeggutor: ["Planta", "Psíquico"],
    Cubone: ["Tierra"],
    Marowak: ["Tierra"],
    Hitmonlee: ["Lucha"],
    Hitmonchan: ["Lucha"],
    Lickitung: ["Normal"],
    Koffing: ["Veneno"],
    Weezing: ["Veneno"],
    Rhyhorn: ["Tierra", "Roca"],
    Rhydon: ["Tierra", "Roca"],
    Chansey: ["Normal"],
    Tangela: ["Planta"],
    Kangaskhan: ["Normal"],
    Horsea: ["Agua"],
    Seadra: ["Agua"],
    Goldeen: ["Agua"],
    Seaking: ["Agua"],
    Staryu: ["Agua"],
    Starmie: ["Agua", "Psíquico"],
    MrMime: ["Psíquico"],
    Scyther: ["Bicho", "Volador"],
    Jynx: ["Hielo", "Psíquico"],
    Electabuzz: ["Eléctrico"],
    Magmar: ["Fuego"],
    Pinsir: ["Bicho"],
    Tauros: ["Normal"],
    Magikarp: ["Agua"],
    Gyarados: ["Agua", "Volador"],
    Lapras: ["Agua", "Hielo"],
    Ditto: ["Normal"],
    Eevee: ["Normal"],
    Vaporeon: ["Agua"],
    Jolteon: ["Eléctrico"],
    Flareon: ["Fuego"],
    Porygon: ["Normal"],
    Omanyte: ["Roca", "Agua"],
    Omastar: ["Roca", "Agua"],
    Kabuto: ["Roca", "Agua"],
    Kabutops: ["Roca", "Agua"],
    Aerodactyl: ["Roca", "Volador"],
    Snorlax: ["Normal"],
    Articuno: ["Hielo", "Volador"],
    Zapdos: ["Eléctrico", "Volador"],
    Moltres: ["Fuego", "Volador"],
    Dratini: ["Dragón"],
    Dragonair: ["Dragón"],
    Dragonite: ["Dragón", "Volador"],
    Mewtwo: ["Psíquico"],
    Mew: ["Psíquico"],
    Chikorita: ["Planta"],
    Bayleef: ["Planta"],
    Meganium: ["Planta"],
    Cyndaquil: ["Fuego"],
    Quilava: ["Fuego"],
    Typhlosion: ["Fuego"],
    Totodile: ["Agua"],
    Croconaw: ["Agua"],
    Feraligatr: ["Agua"],
    Sentret: ["Normal"],
    Furret: ["Normal"],
    Hoothoot: ["Normal", "Volador"],
    Noctowl: ["Normal", "Volador"],
    Ledyba: ["Bicho", "Volador"],
    Ledian: ["Bicho", "Volador"],
    Spinarak: ["Bicho", "Veneno"],
    Ariados: ["Bicho", "Veneno"],
    Crobat: ["Veneno", "Volador"],
    Chinchou: ["Agua", "Eléctrico"],
    Lanturn: ["Agua", "Eléctrico"],
    Pichu: ["Eléctrico"],
    Cleffa: ["Normal"],
    Igglybuff: ["Normal"],
    Togepi: ["Normal"],
    Togetic: ["Normal", "Volador"],
    Natu: ["Psíquico", "Volador"],
    Xatu: ["Psíquico", "Volador"],
    Mareep: ["Eléctrico"],
    Flaaffy: ["Eléctrico"],
    Ampharos: ["Eléctrico"],
    Bellossom: ["Planta"],
    Marill: ["Agua"],
    Azumarill: ["Agua"],
    Sudowoodo: ["Roca"],
    Politoed: ["Agua"],
    Hoppip: ["Planta", "Volador"],
    Skiploom: ["Planta", "Volador"],
    Jumpluff: ["Planta", "Volador"],
    Aipom: ["Normal"],
    Sunkern: ["Planta"],
    Sunflora: ["Planta"],
    Yanma: ["Bicho", "Volador"],
    Wooper: ["Agua", "Tierra"],
    Quagsire: ["Agua", "Tierra"],
    Espeon: ["Psíquico"],
    Umbreon: ["Siniestro"],
    Murkrow: ["Siniestro", "Volador"],
    Slowking: ["Agua", "Psíquico"],
    Misdreavous: ["Fantasma"],
    Unown: ["Psíquico"],
    Wobbuffet: ["Psíquico"],
    Girafarig: ["Normal", "Psíquico"],
    Pineco: ["Bicho"],
    Forretress: ["Bicho", "Acero"],
    Dunsparce: ["Normal"],
    Gligar: ["Tierra", "Volador"],
    Steelix: ["Acero", "Tierra"],
    Snubbull: ["Normal"],
    Granbull: ["Normal"],
    Qwilfish: ["Agua", "Veneno"],
    Scizor: ["Bicho", "Acero"],
    Shuckle: ["Bicho", "Roca"],
    Heracross: ["Bicho", "Lucha"],
    Sneasel: ["Siniestro", "Hielo"],
    Teddiursa: ["Normal"],
    Ursaring: ["Normal"],
    Slugma: ["Fuego"],
    Magcargo: ["Fuego", "Roca"],
    Swinub: ["Hielo", "Tierra"],
    Piloswine: ["Hielo", "Tierra"],
    Corsola: ["Agua", "Roca"],
    Remoraid: ["Agua"],
    Octillery: ["Agua"],
    Delibird: ["Hielo", "Volador"],
    Mantine: ["Agua", "Volador"],
    Skarmory: ["Acero", "Volador"],
    Houndour: ["Siniestro", "Fuego"],
    Houndoom: ["Siniestro", "Fuego"],
    Kingdra: ["Agua", "Dragón"],
    Phanpy: ["Tierra"],
    Donphan: ["Tierra"],
    Porygon2: ["Normal"],
    Stantler: ["Normal"],
    Smeargle: ["Normal"],
    Tyrogue: ["Lucha"],
    Hitmontop: ["Lucha"],
    Smoochum: ["Hielo", "Psíquico"],
    Elekid: ["Eléctrico"],
    Magby: ["Fuego"],
    Miltank: ["Normal"],
    Blissey: ["Normal"],
    Raikou: ["Eléctrico"],
    Entei: ["Fuego"],
    Suicune: ["Agua"],
    Larvitar: ["Roca", "Tierra"],
    Pupitar: ["Roca", "Tierra"],
    Tyranitar: ["Roca", "Siniestro"],
    Lugia: ["Psíquico", "Volador"],
    Ho_oh: ["Fuego", "Volador"],
    Celebi: ["Psíquico", "Planta"],
    Treecko: ["Planta"],
    Grovyle: ["Planta"],
    Sceptile: ["Planta"],
    Torchic: ["Fuego"],
    Combusken: ["Fuego", "Lucha"],
    Blaziken: ["Fuego", "Lucha"],
    Mudkip: ["Agua"],
    Marshtomp: ["Agua", "Tierra"],
    Swampert: ["Agua", "Tierra"],
    Poochyena: ["Siniestro"],
    Mightyena: ["Siniestro"],
    Zigzagoon: ["Normal"],
    Linoone: ["Normal"],
    Wurmple: ["Bicho"],
    Silcoon: ["Bicho"],
    Beautifly: ["Bicho", "Volador"],
    Cascoon: ["Bicho"],
    Dustox: ["Bicho", "Veneno"],
    Lotad: ["Agua", "Planta"],
    Lombre: ["Agua", "Planta"],
    Ludicolo: ["Agua", "Planta"],
    Seedot: ["Planta"],
    Nuzleaf: ["Planta", "Siniestro"],
    Shiftry: ["Planta", "Siniestro"],
    Taillow: ["Normal", "Volador"],
    Swellow: ["Normal", "Volador"],
    Wingull: ["Agua", "Volador"],
    Pelipper: ["Agua", "Volador"],
    Ralts: ["Psíquico"],
    Kirlia: ["Psíquico"],
    Gardevoir: ["Psíquico"],
    Surskit: ["Bicho", "Agua"],
    Masquerain: ["Bicho", "Volador"],
    Shroomish: ["Planta"],
    Breloom: ["Planta", "Lucha"],
    Slakoth: ["Normal"],
    Vigoroth: ["Normal"],
    Slaking: ["Normal"],
    Nincada: ["Bicho", "Tierra"],
    Ninjask: ["Bicho", "Volador"],
    Shedinja: ["Bicho", "Fantasma"],
    Whismur: ["Normal"],
    Loudred: ["Normal"],
    Exploud: ["Normal"],
    Makuhita: ["Lucha"],
    Hariyama: ["Lucha"],
    Azurill: ["Normal"],
    Nosepass: ["Roca"],
    Skitty: ["Normal"],
    Delcatty: ["Normal"],
    Sableye: ["Siniestro", "Fantasma"],
    Mawile: ["Acero"],
    Aron: ["Acero", "Roca"],
    Lairon: ["Acero", "Roca"],
    Aggron: ["Acero", "Roca"],
    Meditite: ["Lucha", "Psíquico"],
    Medicham: ["Lucha", "Psíquico"],
    Electrike: ["Eléctrico"],
    Manectric: ["Eléctrico"],
    Plusle: ["Eléctrico"],
    Minun: ["Eléctrico"],
    Volbeat: ["Bicho"],
    Illumise: ["Bicho"],
    Roselia: ["Planta", "Veneno"],
    Gulpin: ["Veneno"],
    Swalot: ["Veneno"],
    Carvanha: ["Agua", "Siniestro"],
    Sharpedo: ["Agua", "Siniestro"],
    Wailmer: ["Agua"],
    Wailord: ["Agua"],
    Numel: ["Fuego", "Tierra"],
    Camerupt: ["Fuego", "Tierra"],
    Torkoal: ["Fuego"],
    Spoink: ["Psíquico"],
    Grumpig: ["Psíquico"],
    Spinda: ["Normal"],
    Trapinch: ["Tierra"],
    Vibrava: ["Tierra", "Dragón"],
    Flygon: ["Tierra", "Dragón"],
    Cacnea: ["Planta"],
    Cacturne: ["Planta", "Siniestro"],
    Swablu: ["Normal", "Volador"],
    Altaria: ["Dragón", "Volador"],
    Zangoose: ["Normal"],
    Seviper: ["Veneno"],
    Lunatone: ["Roca", "Psíquico"],
    Solrock: ["Roca", "Psíquico"],
    Barboach: ["Agua", "Tierra"],
    Whiscash: ["Agua", "Tierra"],
    Corphish: ["Agua"],
    Crawdaunt: ["Agua", "Siniestro"],
    Baltoy: ["Tierra", "Psíquico"],
    Claydol: ["Tierra", "Psíquico"],
    Lileep: ["Roca", "Planta"],
    Cradily: ["Roca", "Planta"],
    Anorith: ["Roca", "Bicho"],
    Armaldo: ["Roca", "Bicho"],
    Feebas: ["Agua"],
    Milotic: ["Agua"],
    Castform: ["Normal"],
    Kecleon: ["Normal"],
    Shuppet: ["Fantasma"],
    Banette: ["Fantasma"],
    Duskull: ["Fantasma"],
    Dusclops: ["Fantasma"],
    Tropius: ["Planta", "Volador"],
    Chimecho: ["Psíquico"],
    Absol: ["Siniestro"],
    Wynaut: ["Psíquico"],
    Snorunt: ["Hielo"],
    Glalie: ["Hielo"],
    Spheal: ["Hielo", "Agua"],
    Sealeo: ["Hielo", "Agua"],
    Walrein: ["Hielo", "Agua"],
    Clamperl: ["Agua"],
    Huntail: ["Agua"],
    Gorebyss: ["Agua"],
    Relicanth: ["Agua", "Roca"],
    Luvdisc: ["Agua"],
    Bagon: ["Dragón"],
    Shelgon: ["Dragón"],
    Salamence: ["Dragón", "Volador"],
    Beldum: ["Acero", "Psíquico"],
    Metang: ["Acero", "Psíquico"],
    Metagross: ["Acero", "Psíquico"],
    Regirock: ["Roca"],
    Regice: ["Hielo"],
    Registeel: ["Acero"],
    Latias: ["Dragón", "Psíquico"],
    Latios: ["Dragón", "Psíquico"],
    Kyogre: ["Agua"],
    Groudon: ["Tierra"],
    Rayquaza: ["Dragón", "Volador"],
    Jirachi: ["Acero", "Psíquico"],
    Deoxys: ["Psíquico"],
    Turtwig: ["Planta"],
    Grotle: ["Planta"],
    Torterra: ["Planta", "Tierra"],
    Chimchar: ["Fuego"],
    Monferno: ["Fuego", "Lucha"],
    Infernape: ["Fuego", "Lucha"],
    Piplup: ["Agua"],
    Prinplup: ["Agua"],
    Empoleon: ["Agua", "Acero"],
    Starly: ["Normal", "Volador"],
    Staravia: ["Normal", "Volador"],
    Staraptor: ["Normal", "Volador"],
    Bidoof: ["Normal"],
    Bibarel: ["Normal", "Agua"],
    Kricketot: ["Bicho"],
    Kricketune: ["Bicho"],
    Shinx: ["Eléctrico"],
    Luxio: ["Eléctrico"],
    Luxray: ["Eléctrico"],
    Budew: ["Planta", "Veneno"],
    Roserade: ["Planta", "Veneno"],
    Cranidos: ["Roca"],
    Rampardos: ["Roca"],
    Shieldon: ["Roca", "Acero"],
    Bastiodon: ["Roca", "Acero"],
    Burmy: ["Bicho"],
    Wormadam: ["Bicho", "Planta"],
    Mothim: ["Bicho", "Volador"],
    Combee: ["Bicho", "Volador"],
    Vespiquen: ["Bicho", "Volador"],
    Pachirisu: ["Eléctrico"],
    Buizel: ["Agua"],
    Floatzel: ["Agua"],
    Cherubi: ["Planta"],
    Cherrim: ["Planta"],
    Shellos: ["Agua"],
    Gastrodon: ["Agua", "Tierra"],
    Ambipom: ["Normal"],
    Drifloon: ["Fantasma", "Volador"],
    Drifblim: ["Fantasma", "Volador"],
    Buneary: ["Normal"],
    Lopunny: ["Normal"],
    Mismagius: ["Fantasma"],
    Honchkrow: ["Siniestro", "Volador"],
    Glameow: ["Normal"],
    Purugly: ["Normal"],
    Chingling: ["Psíquico"],
    Stunky: ["Veneno", "Siniestro"],
    Skuntank: ["Veneno", "Siniestro"],
    Bronzor: ["Acero", "Psíquico"],
    Bronzong: ["Acero", "Psíquico"],
    Bonsly: ["Roca"],
    MimeJr: ["Psíquico"],
    Happiny: ["Normal"],
    Chatot: ["Normal", "Volador"],
    Spiritomb: ["Fantasma", "Siniestro"],
    Gible: ["Dragón", "Tierra"],
    Gabite: ["Dragón", "Tierra"],
    Garchomp: ["Dragón", "Tierra"],
    Munchlax: ["Normal"],
    Riolu: ["Lucha"],
    Lucario: ["Lucha", "Acero"],
    Hippopotas: ["Tierra"],
    Hippowdon: ["Tierra"],
    Skorupi: ["Veneno", "Bicho"],
    Drapion: ["Veneno", "Siniestro"],
    Croagunk: ["Veneno", "Lucha"],
    Toxicroak: ["Veneno", "Lucha"],
    Carnivine: ["Planta"],
    Finneon: ["Agua"],
    Lumineon: ["Agua"],
    Mantyke: ["Agua", "Volador"],
    Snover: ["Planta", "Hielo"],
    Abomasnow: ["Planta", "Hielo"],
    Weavile: ["Siniestro", "Hielo"],
    Magnezone: ["Eléctrico", "Acero"],
    Lickilicky: ["Normal"],
    Rhyperior: ["Tierra", "Roca"],
    Tangrowth: ["Planta"],
    Electivire: ["Eléctrico"],
    Magmortar: ["Fuego"],
    Togekiss: ["Normal", "Volador"],
    Yanmega: ["Bicho", "Volador"],
    Leafeon: ["Planta"],
    Glaceon: ["Hielo"],
    Gliscor: ["Tierra", "Volador"],
    Mamoswine: ["Hielo", "Tierra"],
    Porygon_Z: ["Normal"],
    Gallade: ["Psíquico", "Lucha"],
    Probopass: ["Roca", "Acero"],
    Dusknoir: ["Fantasma"],
    Froslass: ["Hielo", "Fantasma"],
    Rotom: ["Eléctrico", "Fantasma"],
    Uxie: ["Psíquico"],
    Mesprit: ["Psíquico"],
    Azelf: ["Psíquico"],
    Dialga: ["Acero", "Dragón"],
    Palkia: ["Agua", "Dragón"],
    Heatran: ["Fuego", "Acero"],
    Regigigas: ["Normal"],
    Giratina: ["Fantasma", "Dragón"],
    Cresselia: ["Psíquico"],
    Phione: ["Agua"],
    Manaphy: ["Agua"],
    Darkrai: ["Siniestro"],
    Shaymin: ["Planta"],
    Arceus: ["Normal"],
    Victini: ["Psíquico", "Fuego"],
    Snivy: ["Planta"],
    Servine: ["Planta"],
    Serperior: ["Planta"],
    Tepig: ["Fuego"],
    Pignite: ["Fuego", "Lucha"],
    Emboar: ["Fuego", "Lucha"],
    Oshawott: ["Agua"],
    Dewott: ["Agua"],
    Samurott: ["Agua"],
    Patrat: ["Normal"],
    Watchog: ["Normal"],
    Lillipup: ["Normal"],
    Herdier: ["Normal"],
    Stoutland: ["Normal"],
    Purrloin: ["Siniestro"],
    Liepard: ["Siniestro"],
    Pansage: ["Planta"],
    Simisage: ["Planta"],
    Pansear: ["Fuego"],
    Simisear: ["Fuego"],
    Panpour: ["Agua"],
    Simipour: ["Agua"],
    Munna: ["Psíquico"],
    Musharna: ["Psíquico"],
    Pidove: ["Normal", "Volador"],
    Tranquill: ["Normal", "Volador"],
    Unfezant: ["Normal", "Volador"],
    Blitzle: ["Eléctrico"],
    Zebstrika: ["Eléctrico"],
    Roggenrola: ["Roca"],
    Boldore: ["Roca"],
    Gigalith: ["Roca"],
    Woobat: ["Psíquico", "Volador"],
    Swoobat: ["Psíquico", "Volador"],
    Drilbur: ["Tierra"],
    Excadrill: ["Tierra", "Acero"],
    Audino: ["Normal"],
    Timburr: ["Lucha"],
    Gurdurr: ["Lucha"],
    Conkeldurr: ["Lucha"],
    Tympole: ["Agua"],
    Palpitoad: ["Agua", "Tierra"],
    Seismitoad: ["Agua", "Tierra"],
    Throh: ["Lucha"],
    Sawk: ["Lucha"],
    Sewaddle: ["Bicho", "Planta"],
    Swadloon: ["Bicho", "Planta"],
    Leavanny: ["Bicho", "Planta"],
    Venipede: ["Bicho", "Veneno"],
    Whirlipede: ["Bicho", "Veneno"],
    Scolipede: ["Bicho", "Veneno"],
    Cottonee: ["Planta"],
    Whimsicott: ["Planta"],
    Petilil: ["Planta"],
    Lilligant: ["Planta"],
    Basculin: ["Agua"],
    Sandile: ["Tierra", "Siniestro"],
    Krokorok: ["Tierra", "Siniestro"],
    Krookodile: ["Tierra", "Siniestro"],
    Darumaka: ["Fuego"],
    Darmanitan: ["Fuego"],
    Maractus: ["Planta"],
    Dwebble: ["Bicho", "Roca"],
    Crustle: ["Bicho", "Roca"],
    Scraggy: ["Siniestro", "Lucha"],
    Scrafty: ["Siniestro", "Lucha"],
    Sigilyph: ["Psíquico", "Volador"],
    Yamask: ["Fantasma"],
    Cofagrigus: ["Fantasma"],
    Tirtouga: ["Agua", "Roca"],
    Carracosta: ["Agua", "Roca"],
    Archen: ["Roca", "Volador"],
    Archeops: ["Roca", "Volador"],
    Trubbish: ["Veneno"],
    Garbodor: ["Veneno"],
    Zorua: ["Siniestro"],
    Zoroark: ["Siniestro"],
    Minccino: ["Normal"],
    Cinccino: ["Normal"],
    Gothita: ["Psíquico"],
    Gothorita: ["Psíquico"],
    Gothitelle: ["Psíquico"],
    Solosis: ["Psíquico"],
    Duosion: ["Psíquico"],
    Reuniclus: ["Psíquico"],
    Ducklett: ["Agua", "Volador"],
    Swanna: ["Agua", "Volador"],
    Vanillite: ["Hielo"],
    Vanillish: ["Hielo"],
    Vanilluxe: ["Hielo"],
    Deerling: ["Normal", "Planta"],
    Sawsbuck: ["Normal", "Planta"],
    Emolga: ["Eléctrico", "Volador"],
    Karrablast: ["Bicho"],
    Escavalier: ["Bicho", "Acero"],
    Foongus: ["Planta", "Veneno"],
    Amoonguss: ["Planta", "Veneno"],
    Frillish: ["Agua", "Fantasma"],
    Jellicent: ["Agua", "Fantasma"],
    Alomomola: ["Agua"],
    Joltik: ["Bicho", "Eléctrico"],
    Galvantula: ["Bicho", "Eléctrico"],
    Ferroseed: ["Planta", "Acero"],
    Ferrothorn: ["Planta", "Acero"],
    Klink: ["Acero"],
    Klang: ["Acero"],
    Klinklang: ["Acero"],
    Tynamo: ["Eléctrico"],
    Eelektrik: ["Eléctrico"],
    Eelektross: ["Eléctrico"],
    Elgyem: ["Psíquico"],
    Beheeyem: ["Psíquico"],
    Litwick: ["Fantasma", "Fuego"],
    Lampent: ["Fantasma", "Fuego"],
    Chandelure: ["Fantasma", "Fuego"],
    Axew: ["Dragón"],
    Fraxure: ["Dragón"],
    Haxorus: ["Dragón"],
    Cubchoo: ["Hielo"],
    Beartic: ["Hielo"],
    Cryogonal: ["Hielo"],
    Shelmet: ["Bicho"],
    Accelgor: ["Bicho"],
    Stunfisk: ["Tierra", "Eléctrico"],
    Mienfoo: ["Lucha"],
    Mienshao: ["Lucha"],
    Druddigon: ["Dragón"],
    Golett: ["Tierra", "Fantasma"],
    Golurk: ["Tierra", "Fantasma"],
    Pawniard: ["Siniestro", "Acero"],
    Bisharp: ["Siniestro", "Acero"],
    Bouffalant: ["Normal"],
    Rufflet: ["Normal", "Volador"],
    Braviary: ["Normal", "Volador"],
    Vullaby: ["Siniestro", "Volador"],
    Mandibuzz: ["Siniestro", "Volador"],
    Heatmor: ["Fuego"],
    Durant: ["Bicho", "Acero"],
    Deino: ["Siniestro", "Dragón"],
    Zweilous: ["Siniestro", "Dragón"],
    Hydreigon: ["Siniestro", "Dragón"],
    Larvesta: ["Bicho", "Fuego"],
    Volcarona: ["Bicho", "Fuego"],
    Cobalion: ["Acero", "Lucha"],
    Terrakion: ["Roca", "Lucha"],
    Virizion: ["Planta", "Lucha"],
    Tornadus: ["Volador"],
    Thundurus: ["Eléctrico", "Volador"],
    Reshiram: ["Dragón", "Fuego"],
    Zekrom: ["Dragón", "Eléctrico"],
    Landorus: ["Tierra", "Volador"],
    Kyurem: ["Dragón", "Hielo"],
    Keldeo: ["Agua", "Lucha"],
    Meloetta: ["Normal", "Psíquico"],
    Genesect: ["Bicho", "Acero"],
};




console.log("Pokemones cargados:", pokemones); // Depuración

export { pokemones };
